# Generated by Django 4.1.5 on 2023-01-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('titulo', models.CharField(choices=[('1', 'Problema com uma eleição'), ('2', 'Problema com Site'), ('3', 'Problema com conta')], max_length=1)),
                ('balao', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('N_Eleicao', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Titulo', models.CharField(max_length=30)),
                ('Data', models.DateField(null=True)),
                ('End_Data', models.DateField(null=True)),
                ('Descricao', models.CharField(max_length=150, null=True)),
                ('Ativo', models.BooleanField()),
                ('Cargo', models.CharField(choices=[('1', 'Todos'), ('2', 'Discentes'), ('3', 'Docentes'), ('4', 'Reitores'), (5, 'Tercerizado'), ('6', 'Bolsistas'), ('7', 'Dicentes  & Bolsistas'), ('8', 'Dicentes & Docentes'), ('9', 'Docentes & Reitores'), ('10', 'Discentes & Tercerizados'), ('11', 'Docentes, Reitores & Bolsistas'), ('12', 'Discente, Docentes & Bolsistas'), ('13', 'Docentes, Reitores & Tercerizados'), ('14', 'Discentes, Bolsistas & Tercerizados'), ('15', 'Docentes, Reitores, Bolsistas & Tercerizados'), ('16', 'Docentes, Reitores, Discentes & Tercerizados')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id_Academico', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('Nome', models.CharField(max_length=50)),
                ('CPF', models.CharField(max_length=11, unique=True)),
                ('Genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Senha', models.CharField(max_length=50)),
                ('Foto', models.ImageField(default=None, upload_to='profile', verbose_name='Imagem do perfil')),
                ('Cargo', models.CharField(choices=[('0', 'None'), ('1', 'Discente'), ('2', 'Docente'), ('3', 'Tercerizado'), ('4', 'Bolsista'), ('5', 'Reitor')], max_length=1)),
                ('Foto_Cargo', models.ImageField(default=None, upload_to='Cargo_profile', verbose_name='Cargo info')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('N_Eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.election')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
        migrations.AddField(
            model_name='election',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
        ),
        migrations.CreateModel(
            name='Data_Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidatos', models.CharField(max_length=50)),
                ('N_Candidato', models.IntegerField()),
                ('Votos', models.IntegerField()),
                ('N_Eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.election')),
            ],
        ),
    ]
