# Generated by Django 4.1.5 on 2023-01-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Senha',
            field=models.CharField(max_length=300),
        ),
    ]
